"""add Micro schema

Revision ID: 144851ce0c99
Revises: 
Create Date: 2023-06-19 13:40:10.057964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144851ce0c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('micro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('male_minimum', sa.Integer(), nullable=True),
    sa.Column('female_minimum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('micro')
    # ### end Alembic commands ###
