"""empty message

Revision ID: 6638dad9acbf
Revises: 33a207465981
Create Date: 2023-06-19 14:00:00.433268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6638dad9acbf'
down_revision = '33a207465981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('micro', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
