"""add bmi

Revision ID: db0fafeeb3d4
Revises: ebc5c84709cc
Create Date: 2023-06-19 15:03:28.353590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0fafeeb3d4'
down_revision = 'ebc5c84709cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bmi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
